--- # Master Playbook for Webservers
- hosts: apacheweb
  user: sajj
  sudo: yes
  connection: ssh
  pre_tasks: 
  - name: When did the role start
    raw: echo "Start Of Task" > /home/sajj/time.log
    raw: date >> /home/sajj/time.log
  roles:
    - debian_webservers
  post_tasks:
  - name: When did the role end
    raw: echo "End of Task" >> /home/sajj/time.log
    raw: date >> /home/sajj/time.log
  
