--- # Master Playbook for Webservers
- hosts: '{{ hosts }}'
  user: sajj
  sudo: yes
  connection: ssh
  pre_tasks: 
  - name: When did the role start
    raw: echo "Start Of Task" > /home/sajj/time.log
    raw: date >> /home/sajj/time.log
  roles:
  - { role: redhat_webservers, when: "ansible_os_family == 'RedHat'" }
  - { role: debian_webservers, when: "ansible_os_family == 'Debian'" }
  post_tasks:
  - name: When did the role end
    raw: echo "End of Task" >> /home/sajj/time.log
    raw: date >> /home/sajj/time.log
  
