--- # Master Playbook Demostrating the delegateto command
- hosts: apacheweb
  user: sajj
  sudo: yes
  connection: ssh
  pre_tasks: 
  - name: Ping the Appliction Server
    local_action: raw ping -c 4 172.31.4.194 > /home/sajj/ansible-playbooks-practice/Playbooks/Roles/roles/ping.out
  roles:
  - webservers
  
