- name: Install (Redhat/CentOs) Apache Web Server
  yum: name={{ redhat_apache }} state=latest
  when: "ansible_os_family == 'RedHat' "
- name: Wait for the Service to start listening on port 80
  wait_for:
    port: 80
    state: started
  ignore_errors: yes
