--- # Outline to Playbook Translation 
- hosts: test 
  remote_user: ansible 
  become: yes 
  become_method: sudo 
  gather_facts: no 
  tasks: 
  - name: date/time stamp for when the playbook start 
    command: /usr/bin/date 
    register: timestamp_start 
  - debug: var=timestamp_start 
  - name: install the apache web server 
    yum: pkg=httpd state=latest 
  notify: 
    - Start HTTPD 
    - Capture Status of HTTPD 
    - Display Result of Status 
  - name: install client software - telnet 
    yum: pkg=telnet state=latest 
  - name: install client software - lynx 
    yum: pkg=lynx state=latest 
  - name: log all the packages install on the system 
    command: yum list installed 
    register: installed_result 
  - debug: var=installed_result 
  - name: date/time stamp for when the playbook ends 
    command: /usr/bin/date 
    register: timestamp_end 
  - debug: var=timestamp_end 
  handlers: 
  - name: Start HTTPD 
    service: name=httpd state=restarted 
  - name: Capture Status of HTTPD 
    command: systemctl status httpd 
    register: result 
  - name: Display Result of Status 
    debug: var=result

