--- # FULL INCLUDE TASKS EXAMPLE
- hosts: apacheweb
  user: sajj
  sudo: yes
  connection: ssh
  gather_facts: no
  tasks:
    - include: plays/packages.yml
    - name: Verify the telnet package is inatlled
      raw: yum list installed | grep telnet > /home/sajj/pkg.log
