--- # LOOP PLAYBOOK EXAMPLE

- hosts: apacheweb
  user: sajj
  sudo: yes
  connection: ssh
  gather_facts: no
  tasks:
    - name: Add a list of User
      user: name={{ item }} state=present
      with_items:
        - user1
        - user2
        - user3 
