--- # Script Module Example
- hosts: apacheweb
  user: sajj
  sudo: yes
  connection: ssh
  gather_facts: no
  tasks:
   - script: /home/sajj/Playbooks/systemuptime.sh creates=/home/sajj/Playbooks/uptime.log
